[project]
name = "reachy-mini"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "reachy-mini",
    "openwakeword==0.4.0",
    "pyaudio==0.2.14"
]
